
version: '3'

services:

  cache:
    image: seanhoughton/nginx-cache:test
    ports:
      - 8081:80
    environment:
      LISTENPORT: 80
      VERBOSE: 1
      UPSTREAM: ct-host-u118.ct.activision.com:3333
      UPSTREAM_OPTS: max_fails=3 fail_timeout=30s
      UPSTREAM_PROTOCOL: http
      CACHE_SIZE: 1000M
      WORKERS: auto
      MAX_EVENTS: 1000
      USE_PERFLOG: 0
      SSL: 'off'
